# Generated by Django 3.1 on 2020-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
