# Generated by Django 3.1 on 2020-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactrecords_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecords',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
